### ISSUE TITLE
Error when running `jupctl up`: AttributeError: 'dict' object has no attribute 'id'

### ISSUE THREAD

**Issue by munshkr** [nuxion/labmachine#1]
```
poetry run jupctl up --from-module labmachine_example.lab_cpu --wait
⠹ Starting lab creation
Traceback (most recent call last):
  File "/home/munshkr/.cache/pypoetry/virtualenvs/labmachine-example-Uaocb8NZ-py3.10/bin/jupctl", line 8, in <module>
    sys.exit(cli())
  File "/home/munshkr/.cache/pypoetry/virtualenvs/labmachine-example-Uaocb8NZ-py3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/munshkr/.cache/pypoetry/virtualenvs/labmachine-example-Uaocb8NZ-py3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/munshkr/.cache/pypoetry/virtualenvs/labmachine-example-Uaocb8NZ-py3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/munshkr/.cache/pypoetry/virtualenvs/labmachine-example-Uaocb8NZ-py3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/munshkr/.cache/pypoetry/virtualenvs/labmachine-example-Uaocb8NZ-py3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/munshkr/.cache/pypoetry/virtualenvs/labmachine-example-Uaocb8NZ-py3.10/lib/python3.10/site-packages/labmachine/cli.py", line 227, in jupyter_up
    rsp = shortcuts.lab_from_module(from_module)
  File "/home/munshkr/.cache/pypoetry/virtualenvs/labmachine-example-Uaocb8NZ-py3.10/lib/python3.10/site-packages/labmachine/shortcuts.py", line 16, in lab_from_module
    rsp = jup.create_lab(**cfg.INSTANCE.dict())
  File "/home/munshkr/.cache/pypoetry/virtualenvs/labmachine-example-Uaocb8NZ-py3.10/lib/python3.10/site-packages/labmachine/jupyter.py", line 393, in create_lab
    record.id = data.id
AttributeError: 'dict' object has no attribute 'id'
make: *** [Makefile:10: cpu] Error 1
```

**Comment by munshkr** [comment]
Sorry, this was fixed already (not in the published version)
